### PR TITLE
Added Seconds in exit message

### PR DESCRIPTION
**Pull request by udaysk3**

### CODE REVIEW

**Comment by afr4z** [comment]
i think the logic is still not right, as the seconds could be greater still, so a better way would be to get the entry time and exit time both in seconds, and then convert the difference (in seconds) to hours and minutes

**Comment by udaysk3** [comment]
I have changed the logic accordingly. Please review it once!

**Comment by afr4z** [comment]
bro but still what if the time is 11,45 (entry)  and 12,00 (exit) ? then the time diff in seconds will be 3600*(12-11) + 60*(00-45) right?

**Comment by afr4z** [comment]
id suggest u do entry_time_in_seconds=3600*entry_hours+60*entry_mins+entry_secs
and similiarly exit_time_in_secs and then take the difference
or better yet try to import the time in seconds format, i think its possible using the timestamp()

**Comment by AfthabEK** [comment]
Any updates?

**Pull request closed without merging**
